[client]
showErrorDetails = true
toolbarMode = "viewer"

[server]
port = 8502
headless = true
runOnSave = false
maxUploadSize = 200

[theme]
primaryColor = "#0A71E2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
