[upstox]
access_token="eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI0Q0NXRzciLCJqdGkiOiI2OTRmNTI1YTZhNjY4YjU1YTdmMWJhN2EiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzY2ODA2MTA2LCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NjY4NzI4MDB9.IkwyauwWDSE2sT2AmCoOsFwacfvGKV5rMbs2h50s70g"
api_key="d01c59be-8f1a-46b5-9094-131bcdd05e7b"
api_secret="v6oo0uqmow"
redirect_uri="https://marketmarketmavericksoptionchain.streamlit.app"