[upstox]
access_token="eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI0Q0NXRzciLCJqdGkiOiI2OTU3MzBiOTk3ZTk0ZDI3ODZmNDUzZWMiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzY3MzIxNzg1LCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NjczOTEyMDB9.A0eEsP7D1PhzfS6rrgjxOXIhgRc0vjEMH0-eGFjF84E"
api_key="d01c59be-8f1a-46b5-9094-131bcdd05e7b"
api_secret="v6oo0uqmow"
redirect_uri="https://marketmarketmavericksoptionchain.streamlit.app"